In [12]:
import numpy as np

path = "shard_00010.npz"

data = np.load(path)

print("包含的字段:", data.files)


display(data['text_data'][1000:1010])
display(data['gene_ids'])
display(data['bin_ids'])

# ['gene_ids', 'bin_ids', 'lengths', 'domain_id', 'sample_id', 'text_data', 'text_cols']
display(data['lengths'])

# text_cols=array([
#     'tissue',
#     'region',
#     'sampleType',
#     'compartment',
#     'cellType1',
#     'cellType2',
#     'majorCluster',
#     'subCluster',
#     'sex',
#     'age',
#     'perturbType',
#     'disease',
#     'drug',
#     'dose',
#     'time'
# ], dtype='<U20')



包含的字段: ['gene_ids', 'bin_ids', 'lengths', 'domain_id', 'sample_id', 'text_data', 'text_cols']


array([['lung', 'none', 'none', 'none', 'none', 'none', 'none', 'none',
        'F', 'none', 'trt_cp', 'lung cancer', 'BRD-K19294102', '10',
        '24h'],
       ['lung', 'none', 'none', 'none', 'none', 'none', 'none', 'none',
        'F', 'none', 'trt_cp', 'lung cancer', 'troglitazone', '20',
        '24h'],
       ['lung', 'none', 'none', 'none', 'none', 'none', 'none', 'none',
        'F', 'none', 'trt_cp', 'lung cancer', 'troglitazone', '10',
        '24h'],
       ['lung', 'none', 'none', 'none', 'none', 'none', 'none', 'none',
        'F', 'none', 'trt_cp', 'lung cancer', 'BRD-K77908171', '20',
        '24h'],
       ['lung', 'none', 'none', 'none', 'none', 'none', 'none', 'none',
        'F', 'none', 'trt_cp', 'lung cancer', 'BRD-K77908171', '10',
        '24h'],
       ['lung', 'none', 'none', 'none', 'none', 'none', 'none', 'none',
        'F', 'none', 'trt_cp', 'lung cancer', 'BRD-K02781692', '20',
        '24h'],
       ['lung', 'none', 'none', 'none', 'none', 'none', 'non

array([[ 3173,  5197,  4140, ...,  1453,  2109,  6455],
       [ 3173,   990,  6195, ...,  8903,   586,  5010],
       [ 6271, 11035,  1527, ...,  1668,  1180, 11276],
       ...,
       [ 1296,  8326,  4460, ...,  9273,  8440,  4235],
       [ 1296,  8326,  4460, ..., 11908,  7655,  7357],
       [ 1296,  8326,  4460, ...,   906,  7915,  9240]],
      shape=(63479, 1024), dtype=int32)

array([[32, 32, 32, ...,  1,  1,  1],
       [32, 32, 32, ...,  1,  1,  1],
       [32, 32, 32, ...,  1,  1,  1],
       ...,
       [32, 32, 32, ...,  1,  1,  1],
       [32, 32, 32, ...,  1,  1,  1],
       [32, 32, 32, ...,  1,  1,  1]], shape=(63479, 1024), dtype=int16)

array([1024, 1024, 1024, ..., 1024, 1024, 1024],
      shape=(63479,), dtype=int16)